// <auto-generated />
using System;
using MASB.MyAirport.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MASB.MyAirport.EF.Migrations
{
    [DbContext(typeof(MyAirportContext))]
    partial class MyAirportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MASB.MyAirport.EF.Bagage", b =>
                {
                    b.Property<int>("BagageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CLASSE")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CODE_IATA")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("DATA_CREATION")
                        .HasColumnType("datetime2");

                    b.Property<string>("DESTINATION")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("ESCALE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("PRIORITAIRE")
                        .HasColumnType("tinyint");

                    b.Property<string>("SSUR")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("STA")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("VolID")
                        .HasColumnType("int");

                    b.HasKey("BagageID");

                    b.HasIndex("VolID");

                    b.ToTable("Bagage");
                });

            modelBuilder.Entity("MASB.MyAirport.EF.Vol", b =>
                {
                    b.Property<int>("VolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CIE")
                        .HasColumnType("int");

                    b.Property<string>("DES")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("DHC")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMM")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("JEK")
                        .HasColumnType("int");

                    b.Property<string>("LIG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PAX")
                        .HasColumnType("int");

                    b.Property<string>("PKG")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("VolID");

                    b.ToTable("Vol");
                });

            modelBuilder.Entity("MASB.MyAirport.EF.Bagage", b =>
                {
                    b.HasOne("MASB.MyAirport.EF.Vol", "Vol")
                        .WithMany()
                        .HasForeignKey("VolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
